#Connect Jason script to GPT API
#This code is generated by ChatGPT
#Not running
#Python Version 3.9.0

import openai
import json

# Set your OpenAI API key
openai.api_key = "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"

# Define the JSON input with the prompt in the "text" field
input_json = {
    "text": "Hello, ChatGPT! How can you help me today?"
}

# Convert the JSON object to a string
input_string = json.dumps(input_json)

# Make a request to the OpenAI API using the correct endpoint
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Hello, ChatGPT! How can you help me today?"}
    ]
)

# Extract relevant information
model_reply = response['choices'][0]['message']['content']

# Create a dictionary with the information you want to save
output_data = {
    "input": input_json,
    "model_reply": model_reply
}

# Convert the dictionary to a JSON string
output_json_string = json.dumps(output_data, indent=2)

# Write the JSON string to a file
with open('output.json', 'w') as file:
    file.write(output_json_string)

# Print the model's reply
print(model_reply)

